### PR TITLE
Declare add-on stable: version 2019.1, according with year version of…

### PR DESCRIPTION
**Pull request by nvdaes**
… NVDA and previous number

### CODE REVIEW

**Comment by nvdaes** [comment]
@CyrilleB79, if you want, review this PR before declaring it stable.
Thanks

**Comment by CyrilleB79** [comment]
@nvdaes, what should be reviewed exactly?
The diff of this PR consists only in one line (the version).
Sorry, I did not follow so much the new process proposal with reviews; it is time to learn for me.

**Comment by nvdaes** [comment]
HI, you can approve the pull request in case you consider that the add-on is enough stable to release the stable version, not dev. Thanks for your comment.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
@CyrilleB79 , thanks for your review. I will release stable version 2019.1 now. Let's post on the website stable section when final version of NVDA is released.

**Pull request merged**
