### PR TITLE
Add ability to config keys to confirm/cancel when typing with one hand

### PR DESCRIPTION
**Pull request by nvdaes**
## Link to issue number:
None
### Summary of the issue:
Sometimes maybe tiring to use the same finger to confirm and cancel when typing with one hand (g,h, t, y), as reported privately.
### Description of how this pull request fixes the issue:
- Added two edit boxes to config what keyswill beused to confirm/cancel. This ensuresthat keys will be characters, avoiding create functionsto capture gestures, that maybe more difficult to handle also for users.
- The plugin willtransform these characters in instances of keyboardHandler.KeyboardInputGesture to find out the vkCode of each one.
- If a code matches a dot it will not be used.
- If a codetocancelis used to confirm, it will  not be used.
- We avoid present error messages forsimplicity.
### Testing performed:
Tested  locally in different profiles.
### Known issues with pull request:
We may improve this converting characters to uppercase.
### Change log entry:
- Added ability to configure keys used to confirm/cancel when typing with one hand.

### CODE REVIEW

**Comment by nvdaes** [comment]
cc: @CyrilleB79

**Comment by CyrilleB79** [comment]
Tested on French Keyboard.

It is working well with any key that does not produce a dot and that issues a character, i.e:
²&é"'(-è_çà)=$ù*<,;:!

Special note: it even works with the "^ key" (located at the right of the P), which is a dead key.

**Comment by nvdaes** [comment]
@CyrilleB79 , thanks for testing.
I was also requested to add ability to send dots typed with one hand every second. I think this may not be always useful, but finally I created it. I'll merge this during this week if possible.
Cheers

**Comment by CyrilleB79** [comment]
Hi Noelia

I have had a look at the new dev in this PR. I have two remarks:
1. The documentation is not up-to-date with the new options. They really need to be explained somewhere.
2. IMO, the automatic validation timeout should be finely configurable, e.g. each 0.1, 0.2 or 0.25 second between 0 and 5 seconds. Indeed, even if almost no one will use this feature, I imagine that each one of the few ones needing it will have very specific needs.



4.

**Comment by nvdaes** [comment]
Hi Cyrille, I've addressed your comments.
Timeout canbe set from 0 to 2000 milliseconds, like the advanced option for cursor in NVDA. Default is 0, that is, confirm keys are needed to send dots. But your idea is great! I've tested this feature with timeout set to 100  ms and seems comfortable. Thanks!

**Comment by nvdaes** [comment]
Let's merge this now.

**Pull request merged**
